server:
  port: 8081
spring:
  data:
    mongodb:
      host: 192.168.198.71
      database: drgs-report
      port: 27017
#  data:
#    mongodb:
#      uri: mongodb://192.168.198.71:27017
#      database: record
#  jpa:
#    properties:
#      hibernate:
#          hbm2ddl:
#            auto: create
#  datasource:
#    url: jdbc:mysql://localhost:3306/LoadOrder
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

test:
  str: 123